### ISSUE TITLE
Remove scrollify

### ISSUE THREAD

**Issue by afuhrtrumpet** [CWDG/design-circle#10]
Don't know if this is at all possible, but scrolling is still a very frustrating experience. If it could be revised to have less lag, that would be good.

**Comment by J3RN** [comment]
I like the idea of something less intrusive, like on [Thoughtbot's website](https://thoughtbot.com/), or non-existent, with full-page sections, like the [Shift Creator Space](http://creatorspace.co/).

Anyway, the plugin we use is [Scrollify](http://projects.lukehaas.me/scrollify/#home), but I feel like it's just going to be pain and sadness.

**Comment by J3RN** [comment]
@Finnbar22 Since I originally put this in, I figured I'd help you out with taking it out.
- Remove `js/jquery.scrollify.min.js`
- Remove everything in `js/main.js` that says anything about `scrollify`. Which is just about everything other than the second line that sets the height of each `.section`.

That should be it!

**Comment by Finnbar22** [comment]
@J3RN Awesome. I'll go ahead and do that and also look at some other avenues we could look into for better scrolling.

**Comment by afuhrtrumpet** [comment]
Let's use http://benoit.pointet.info/stuff/jquery-scrollsnap-plugin/

**Comment by afuhrtrumpet** [comment]
I tried it in the hello-scrollsnap branch, and it doesn't seem to work too well. Interestingly enough, it worked on the mobile layout I am working on (maybe because it uses "fixed" for the content?).

**Comment by J3RN** [comment]
Just a note, this is big and in red on the Scrollsnap website:
**I stopped actively developing and maintaining this plugin in October 2014. Anyone willing to take over is very welcome, just let me know. See possible alternatives hereunder.**

**Comment by J3RN** [comment]
Also, I know this is sort of late in the process to bring this up, but does anyone else like the idea of snapping left-to-right, and then having each section scroll down naturally as far as necessary? I feel like that could be slick.
