### ISSUE TITLE
Make archives link work

### ISSUE THREAD

**Issue by afuhrtrumpet** [CWDG/design-circle#17]
Should transition to the blog archives in some manner.

**Comment by J3RN** [comment]
What do the blog archives look like?

**Comment by mrogman** [comment]
It looks like nothing right now. Well I did make a basic table with a little css styling for the prototype but that was just a placeholder. I'm going to work on this today. I was thinking we at least need a column for the article title, date created, and maybe a subject/topic or something. If there's anything else I should include or you guys have a preference on the styling just let me know.

**Comment by mrogman** [comment]
I think this issue is a duplicate of #8 with respect to the transition. I included one in PR #20 but @J3RN you're welcome to play around with it since alex assigned you this issue.

**Comment by J3RN** [comment]
Since I'm taking on a sort of front-end dev position, I'd be happy to make this pretty and add pagination and everything. That would probably warrant opening a new issue, and shouldn't hold up your PR, though.

**Comment by mrogman** [comment]
Yeah man, go for it. Just wanted to get the basics out there to build off of. I don't think I'm going to work on this anymore before the meeting so I'll just merge what's there if thats cool and you can take it from there.

**Comment by J3RN** [comment]
Well, merging it is up to @afuhrtrumpet. Anyway, thanks for knocking this out! The 'more events' section should be almost identical to this one, so we should see if maybe we can get that assigned to you. We can talk about it more at the meeting tomorrow.

**Comment by mrogman** [comment]
Got it. Sounds good and no problem!
