### ISSUE TITLE
Add image upload

### ISSUE THREAD

**Issue by afuhrtrumpet** [CWDG/design-circle#27]
Being able to specify URLs for images is nice, but being able to upload images for blog posts is better. We should look to the docs for yogiben:meteor-admin to figure this one out.

**Comment by mrogman** [comment]
I can take a look at this if you want

**Comment by afuhrtrumpet** [comment]
Sure. Just make sure you can add yourself as an admin and log in to
meteor-admin.

**Comment by mrogman** [comment]
I don't see anything regarding image uploading in the meteor-admin docs but I've found a couple of other things we can take a look at to achieve this. We can use [GridFS](https://atmospherejs.com/cfs/gridfs) to store images in mongo (though it looks like it isn't recommended for use in production yet), or we could take a look at a 3rd party service like [Cloudinary](http://cloudinary.com/) (free for our purposes) to handle storage and image processing features that can be integrated into the app. Let me know what you guys think.

**Comment by afuhrtrumpet** [comment]
https://github.com/yogiben/meteor-starter has image uploading in their admin interface, so I assume it's built in.

**Comment by mrogman** [comment]
Yep you're right, I see it now. There is an example that uses GridFS (via CollectionFS) for storage and GraphicsMagick for processing

**Comment by afuhrtrumpet** [comment]
Looks like we want to make use of this package with meteor admin: https://atmospherejs.com/yogiben/autoform-file

There's also a handy guide on there for getting started. I'll go ahead and create the branch if you haven't already so we can get this taken care of.

**Comment by mrogman** [comment]
Ok, I've pulled the branch down and gave myself admin access. I'll try to get it working before the meeting

**Comment by afuhrtrumpet** [comment]
Alright. The image upload shows, but I can't figure out how to display the
image (if the image is being stored at all).

**Comment by afuhrtrumpet** [comment]
I was using the guide here if it helps:
https://atmospherejs.com/yogiben/autoform-file
